#!/bin/bash

echo "Setting up GitHub repository for posture-ai-unified..."
echo ""
echo "Since GitHub CLI requires interactive installation, here's what you need to do:"
echo ""
echo "OPTION 1: Manual Setup (Recommended)"
echo "===================================="
echo "1. Open your browser and go to: https://github.com/new"
echo "2. Create a new repository named: posture-ai-unified"
echo "3. Make it private (you can change this later)"
echo "4. Do NOT initialize with README, .gitignore, or license"
echo ""
echo "5. After creating, come back here and run:"
echo "   git remote add origin https://github.com/TheSmilemakers/posture-ai-unified.git"
echo "   git push -u origin main"
echo ""
echo "OPTION 2: Install GitHub CLI"
echo "============================"
echo "1. Open a new terminal window"
echo "2. Install Homebrew (if not installed):"
echo "   /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "3. Install GitHub CLI:"
echo "   brew install gh"
echo ""
echo "4. Authenticate:"
echo "   gh auth login"
echo ""
echo "5. Create repo and push:"
echo "   gh repo create posture-ai-unified --private --source=. --remote=origin --push"
echo ""
echo "Current Git Status:"
echo "==================="
git status --short
echo ""
echo "Your GitHub username is: TheSmilemakers"
echo ""
echo "After pushing, install CodeRabbit at: https://github.com/apps/coderabbitai"